[package]
authors = ["jkilpatr <jkilpatr@redhat.com>"]
name = "babel_monitor"
version = "0.1.0"
edition = "2018"

[dependencies]
ascii = "1.0"
env_logger = "0.7"
failure = "0.1"
ipnetwork = "0.14"
log = "0.4"
futures = "0.1"
tokio = "0.1"
serde = "1.0"
