[package]
authors = ["jkilpatr <jkilpatr@redhat.com>"]
name = "babel_monitor"
version = "0.1.0"
edition = "2018"

[dependencies]
ascii = "1.0"
env_logger = "0.9"
ipnetwork = "0.18"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
