[package]
name = "bounty_hunter"
version = "0.1.0"
authors = ["kingoflolz <wangben3@gmail.com>"]

[dependencies]
log = "0.3"
num256 = { path = "../num256" }
althea_types = { path = "../althea_types" }
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
simple_logger = "0.4.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"

[dependencies.rouille]
version = "2.0"
default-features = false