language: rust
cache: cargo
before_install:
  - sudo add-apt-repository ppa:wireguard/wireguard -y
  - sudo add-apt-repository universe
  - sudo apt-get -qq update
  - sudo apt-get install -y libsqlite3-dev iperf3 python3-pip bridge-utils wireguard linux-source linux-headers-$(uname -r) curl git libssl-dev pkg-config build-essential ipset
  - sudo pip3 install -r integration-tests/requirements.txt
  - which diesel || cargo install diesel_cli --no-default-features --features sqlite
env:
  - TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --write-mode=diff"
  - TEST_COMMAND="cargo build --verbose --all"
  - TEST_COMMAND="./integration-tests/cross-build.sh"
  - TEST_COMMAND="cargo test --verbose --all" RUST_TEST_THREADS=1
  - TEST_COMMAND="./integration-tests/rita.sh" BUILD_BABELD=1 INITIAL_POLL_INTERVAL=10
rust:
  - stable
  - beta
  - nightly
script:
  - (eval "$TEST_COMMAND")
matrix:
  exclude:
  - rust: stable
    env: TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --write-mode=diff"
  - rust: beta
    env: TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --write-mode=diff"
  - rust: stable
    env: TEST_COMMAND="./integration-tests/cross-build.sh"
  - rust: beta
    env: TEST_COMMAND="./integration-tests/cross-build.sh"
