language: rust
cache: cargo
before_install:
  - sudo add-apt-repository ppa:wireguard/wireguard -y
  - sudo add-apt-repository universe
  - sudo apt-get -qq update
  - sudo apt-get install -y libsqlite3-dev iperf3 python3-pip bridge-utils wireguard linux-source linux-headers-$(uname -r) curl git libssl-dev pkg-config build-essential ipset
  - which diesel || cargo install diesel_cli --no-default-features --features sqlite
  - rustup target add powerpc64le-unknown-linux-gnu
  - rustup update
  - sudo cp /usr/include/x86_64-linux-gnu/openssl/* /usr/include/openssl/
env:
  - TEST_COMMAND="rustup component add rustfmt-preview --toolchain nightly && cargo fmt --all -- --check"
  - TEST_COMMAND="cargo build --verbose --all"
  - TEST_COMMAND="./integration-tests/cross-build.sh" 
  - TEST_COMMAND="cargo test --verbose --all" RUST_TEST_THREADS=1
  - TEST_COMMAND="./integration-tests/rita.sh" BUILD_BABELD=1 INITIAL_POLL_INTERVAL=5 BACKOFF_FACTOR="1.5" VERBOSE=1
rust:
  - stable
  - beta
  - nightly
script:
  - (eval "$TEST_COMMAND")
matrix:
  exclude:
  - rust: stable
    env: TEST_COMMAND="rustup component add rustfmt-preview --toolchain nightly && cargo fmt --all -- --check"
  - rust: beta
    env: TEST_COMMAND="rustup component add rustfmt-preview --toolchain nightly && cargo fmt --all -- --check"
  - rust: stable
    env: TEST_COMMAND="./integration-tests/cross-build.sh"
  - rust: beta
    env: TEST_COMMAND="./integration-tests/cross-build.sh"
