[payment]
pay_threshold = "0"
close_threshold = "-1000000000"
close_fraction = "100"
buffer_period = 3
eth_address = "0x0101010101010101010101010101010101010101"

[network]
own_ip = "fd00::1"
bounty_ip = "fd00::3"
babel_port = 6872
rita_hello_port = 4876
rita_contact_port = 4874
rita_dashboard_port = 4877
bounty_port = 8888
wg_private_key = ""
wg_private_key_path = "/tmp/priv"
wg_public_key = ""
wg_start_port = 60000
peer_interfaces = []
manual_peers = []
default_route = []

[exit_client]
wg_listen_port = 59999
lan_nics = ["lo"]