db_file = "exit.db"
description = "just a normal althea exit"

[payment]
pay_threshold = "0"
close_threshold = "-1000000000"
close_fraction = "100"
buffer_period = 3
eth_address = "0x0101010101010101010101010101010101010101"

[network]
own_ip = "fd00::1"
bounty_ip = "fd00::3"
discovery_ip = "ff02::1:8"
babel_port = 6872
rita_hello_port = 4876
rita_contact_port = 4874
rita_dashboard_port = 4877
rita_tick_interval = 5
bounty_port = 8888
wg_private_key = ""
wg_private_key_path = "/tmp/priv"
wg_public_key = ""
wg_start_port = 60000
peer_interfaces = []
tunnel_timeout_seconds = 900
manual_peers = []
external_nic = "veth-5-8"
default_route = []

[exit_network]
wg_tunnel_port = 59999
exit_hello_port = 4875
exit_price = 50
own_internal_ip = "172.168.1.254"
exit_start_ip = "172.168.1.100"
netmask = 24

[dao]
dao_enforcement = false
cache_timeout_seconds = 600
node_list = []
dao_addresses = []

[mailer]
test = true
email_cooldown=60
test_dir = "mail"
from_address = "email-verif@example.com"
