db_file = "../exit_db/test.db"

[payment]
pay_threshold = "0"
close_threshold = "-1000000000"
close_fraction = "100"
buffer_period = 3
eth_address = "0x0101010101010101010101010101010101010101"

[network]
own_ip = "fd::1"
bounty_ip = "fd::3"
babel_port = 8080
rita_port = 4876
bounty_port = 8888
wg_private_key = "4FHz1vrk/IP+2Yzvu215c8wRUTq/QvBpRDxv0ZCLlX4="
wg_private_key_path = "/tmp/priv"
wg_public_key = "GGdAlEoj2NSKhtx7HhyATDDraMwCztQl62qckvrRBU4="
wg_start_port = 60000
peer_interfaces = []
manual_peers = []

[exit_network]
wg_tunnel_port = 59999
external_nic = "veth-5-8"
exit_price = 50
own_internal_ip = "172.168.1.254"
netmask = "255.255.255.0"
