db_uri = "postgres://postgres@localhost/test"
workers = 1
description = "just a normal althea exit"

[payment]
pay_threshold = "0"
close_threshold = "-1000000000"
close_fraction = "100"
buffer_period = 3
eth_address = "0x0101010101010101010101010101010101010101"

[network]
mesh_ip = "fd00::1"
babel_port = 6872
rita_hello_port = 4876
rita_contact_port = 4874
rita_dashboard_port = 4877
rita_tick_interval = 5
wg_public_key = "bvM10HW73yePrxdtCQQ4U20W5ogogdiZtUihrPc/oGY="
wg_private_key = "OGzbcm6czrjOEAViK7ZzlWM8mtjCxp7UPbuLS/dATV4="
wg_private_key_path = "/tmp/priv"
wg_start_port = 60000
tunnel_timeout_seconds = 900
peer_interfaces = []
manual_peers = []
external_nic = "veth-5-8"
default_route = []

[dao]
dao_enforcement = false
cache_timeout_seconds = 600
node_list = []
dao_addresses = []

[exit_network]
wg_tunnel_port = 59999
wg_v2_tunnel_port = 59998
exit_hello_port = 4875
exit_price = 50
own_internal_ip = "172.168.1.254"
exit_start_ip = "172.168.1.100"
netmask = 24
subnet = "fd00::1337/40"
entry_timeout = 7776000
wg_public_key = "H/ABwzXk834OwGYU8CZGfFxNZOd+BAJEaVDHiEiWWhU="
wg_private_key = "ALxcZm2r58gY0sB4vIfnjShc86qBoVK3f32H9VrwqWU="
registered_users_contract_addr = "0x5AeE3Dff733F56cFe7E5390B9cC3A46a90cA1CfA"
wg_private_key_path = "/tmp/exit-priv"
pass = "Some pass here"

[[exit_network.cluster_exits]]
mesh_ip = "fd00::5"
eth_address = "0x5AeE3Dff733F56cFe7E5390B9cC3A46a90cA1CfA"
wg_public_key = "bvM10HW73yePrxdtCQQ4U20W5ogogdiZtUihrPc/oGY="

[verif_settings]
type = "Email"

[verif_settings.contents]
email_cooldown = 60
from_address = "verification@example.com"
smtp_url = "smtp.fastmail.com"
smtp_domain = "mail.example.com"
smtp_username = "changeme"
smtp_password = "changeme"
balance_notification_interval = 600
notify_low_balance = true


[log]
enabled = false
