[payment]
pay_threshold = "0"
close_threshold = "-1000000000"
close_fraction = "100"
buffer_period = 3
eth_address = "0x0101010101010101010101010101010101010101"

[network]
mesh_ip = "fd00::1"
bounty_ip = "fd00::3"
babel_port = 6872
rita_hello_port = 4876
rita_contact_port = 4874
rita_dashboard_port = 4877
rita_tick_interval = 5
bounty_port = 8888
wg_private_key = ""
wg_private_key_path = "/tmp/priv"
wg_public_key = ""
wg_start_port = 60000
tunnel_timeout_seconds = 900
peer_interfaces = []
manual_peers = []
default_route = []
key_path = "key.der"
cert_path = "cert.der"

[exit_client]
wg_listen_port = 59999
lan_nics = ["lo"]

[exit_client.reg_details]
email = "1234@gmail.com"

[exit_client.exits.exit_a]
message = "Registration OK"
registration_port = 4875
state = "Registered"
description = "ExitA"

[exit_client.exits.exit_a.general_details]
description = "just a normal althea exit"
exit_price = 50
netmask = 24
server_internal_ip = "172.168.1.254"
wg_exit_port = 59999

[exit_client.exits.exit_a.id]
eth_address = "0x0101010101010101010101010101010101010101"
mesh_ip = "fd00::5"
wg_public_key = "twSLk4SyWO7rlW6OqJPxFzx6tXUFcVD07tpd0AUCPgE="

[exit_client.exits.exit_a.our_details]
client_internal_ip = "172.168.1.103"

[exit_client.exits.exit_b]
message = "Got info ok"
registration_port = 4875
auto_register = false
state = "GotInfo"
description = "ExitB"

[exit_client.exits.exit_b.general_details]
description = "just a normal althea exit"
exit_price = 50
netmask = 24
server_internal_ip = "172.168.1.254"
wg_exit_port = 59999

[exit_client.exits.exit_b.id]
eth_address = "0x0101010101010101010101010101010101010101"
mesh_ip = "fd00::5"
wg_public_key = "twSLk4SyWO7rlW6OqJPxFzx6tXUFcVD07tpd0AUCPgE="

[exit_client.exits.exit_c]
message = "Pending"
registration_port = 4875
state = "Pending"
description = "ExitC"

[exit_client.exits.exit_c.general_details]
description = "just a normal althea exit"
exit_price = 50
netmask = 24
server_internal_ip = "172.168.1.254"
wg_exit_port = 59999

[exit_client.exits.exit_c.id]
eth_address = "0x0101010101010101010101010101010101010101"
mesh_ip = "fd00::5"
wg_public_key = "twSLk4SyWO7rlW6OqJPxFzx6tXUFcVD07tpd0AUCPgE="

[exit_client.exits.exit_d]
state = "New"
registration_port = 4875
description = "ExitD"

[exit_client.exits.exit_d.id]
eth_address = "0x0101010101010101010101010101010101010101"
mesh_ip = "fd00::5"
wg_public_key = "twSLk4SyWO7rlW6OqJPxFzx6tXUFcVD07tpd0AUCPgE="


[dao]
dao_enforcement = false
cache_timeout_seconds = 600
node_list = []
dao_addresses = []
