[exit_client]
current_exit = "us_west"
lan_nics = ["lan"]
low_balance_notification = true
wg_listen_port = 59999
[exit_client.contact_info.number.code]
source = "plus"
value = 1

[exit_client.contact_info.number.national]
value = 5304703796
zeros = 0
[exit_client.exits.africa]
description = "Althea Africa exit"
message = "Got info successfully"
registration_port = 4875
state = "GotInfo"

[exit_client.exits.africa.general_details]
description = "Althea Africa exit"
exit_currency = "Xdai"
exit_price = 10000000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.exits.africa.id]
eth_address = "0xEba3aF4E87663b3Bb57FC89976502b960e3906ff"
mesh_ip = "fd00::1337:e7f"
wg_public_key = "V0tgdQ2Ljx5xyw4UMQ6a7ZztQmyvqrUp/4jrFcCeG1w="

[exit_client.exits.apac]
description = "In Singapore"
registration_port = 4875
state = "New"

[exit_client.exits.apac.id]
eth_address = "0xE4AD1F9aA23957D294D869B70fC8F28774dF896E"
mesh_ip = "fd00::1337:e4f"
wg_public_key = "1kKSpzdhI4kfqeMqch9I1bXqOUXeKN7EQBecVzW60ys="

[exit_client.exits.ca]
description = "Canada Althea Exit"
registration_port = 4875
state = "New"

[exit_client.exits.ca.id]
eth_address = "0x90b82ED41dCD867Df7d2aedAB62280E82FCd64F3"
mesh_ip = "fd00::1337:3e9f"
wg_public_key = "D0z23bOTn5RQgM87nuxx6zgmFMMAKBHXSOXopHtZhTc="

[exit_client.exits.south_america_eth]
description = "Nodo de salida de America del Sur"
registration_port = 4875
state = "New"

[exit_client.exits.south_america_eth.id]
eth_address = "0x81B6c9F8cfD8f135743A9D39b3b0386024eA4Cc8"
mesh_ip = "fd00::1337:e8f"
wg_public_key = "AlsMwUkJmiA+EQ45p+n+RAtXq1rCA51k58HRwlzoETs="

[exit_client.exits.test]
description = "The Althea testing exit cluster. Unstable!"
message = "Got info successfully"
registration_port = 4875
state = "GotInfo"

[exit_client.exits.test.general_details]
description = "Test cluster: A!"
exit_currency = "Rinkeby"
exit_price = 714000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.exits.test.id]
eth_address = "0x5AeE3Dff733F56cFe7E5390B9cC3A46a90cA1CfA"
mesh_ip = "fd00::1337:1e0f"
wg_public_key = "zgAlhyOQy8crB0ewrsWt3ES9SvFguwx5mq9i2KiknmA="

[exit_client.exits.us_west]
description = "The Althea Production US exit"
message = "Registration OK"
registration_port = 4875
state = "Registered"

[exit_client.exits.us_west.general_details]
description = "Althea San Francisco Exit Equinix"
exit_currency = "Xdai"
exit_price = 10000000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.exits.us_west.id]
eth_address = "0x72d9E579f691D62aA7e0703840db6dd2fa9fAE21"
mesh_ip = "fd00::1337:e2f"
wg_public_key = "jkIodvXKgij/rAEQXFEPJpls6ooxXJEC5XlWA1uUPUg="

[exit_client.exits.us_west.our_details]
client_internal_ip = "172.168.2.146"
[exit_client.new_exits.africa]
description = "Althea Africa exit"
eth_address = "0xEba3aF4E87663b3Bb57FC89976502b960e3906ff"
message = "Got info successfully"
registration_port = 4875
state = "GotInfo"
subnet = "fd00::1337:e7f/128"
subnet_len = 128
wg_public_key = "V0tgdQ2Ljx5xyw4UMQ6a7ZztQmyvqrUp/4jrFcCeG1w="

[exit_client.new_exits.africa.general_details]
description = "Althea Africa exit"
exit_currency = "Xdai"
exit_price = 10000000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.new_exits.africa.id]
eth_address = "0xEba3aF4E87663b3Bb57FC89976502b960e3906ff"
mesh_ip = "fd00::1337:e7f"
wg_public_key = "V0tgdQ2Ljx5xyw4UMQ6a7ZztQmyvqrUp/4jrFcCeG1w="

[exit_client.new_exits.africa.selected_exit]
selected_id = "fd00::1337:e7f"

[exit_client.new_exits.apac]
description = "In Singapore"
eth_address = "0xE4AD1F9aA23957D294D869B70fC8F28774dF896E"
registration_port = 4875
state = "New"
subnet = "fd00::1337:e4f/128"
subnet_len = 128
wg_public_key = "1kKSpzdhI4kfqeMqch9I1bXqOUXeKN7EQBecVzW60ys="

[exit_client.new_exits.apac.id]
eth_address = "0xE4AD1F9aA23957D294D869B70fC8F28774dF896E"
mesh_ip = "fd00::1337:e4f"
wg_public_key = "1kKSpzdhI4kfqeMqch9I1bXqOUXeKN7EQBecVzW60ys="

[exit_client.new_exits.apac.selected_exit]
selected_id = "fd00::1337:e4f"

[exit_client.new_exits.ca]
description = "Canada Althea Exit"
eth_address = "0x90b82ED41dCD867Df7d2aedAB62280E82FCd64F3"
registration_port = 4875
state = "New"
subnet = "fd00::1337:3e9f/128"
subnet_len = 128
wg_public_key = "D0z23bOTn5RQgM87nuxx6zgmFMMAKBHXSOXopHtZhTc="

[exit_client.new_exits.ca.id]
eth_address = "0x90b82ED41dCD867Df7d2aedAB62280E82FCd64F3"
mesh_ip = "fd00::1337:3e9f"
wg_public_key = "D0z23bOTn5RQgM87nuxx6zgmFMMAKBHXSOXopHtZhTc="

[exit_client.new_exits.ca.selected_exit]
selected_id = "fd00::1337:3e9f"

[exit_client.new_exits.south_america_eth]
description = "Nodo de salida de America del Sur"
eth_address = "0x81B6c9F8cfD8f135743A9D39b3b0386024eA4Cc8"
registration_port = 4875
state = "New"
subnet = "fd00::1337:e8f/128"
subnet_len = 128
wg_public_key = "AlsMwUkJmiA+EQ45p+n+RAtXq1rCA51k58HRwlzoETs="

[exit_client.new_exits.south_america_eth.id]
eth_address = "0x81B6c9F8cfD8f135743A9D39b3b0386024eA4Cc8"
mesh_ip = "fd00::1337:e8f"
wg_public_key = "AlsMwUkJmiA+EQ45p+n+RAtXq1rCA51k58HRwlzoETs="

[exit_client.new_exits.south_america_eth.selected_exit]
selected_id = "fd00::1337:e8f"

[exit_client.new_exits.test]
description = "The Althea testing exit cluster. Unstable!"
eth_address = "0x5AeE3Dff733F56cFe7E5390B9cC3A46a90cA1CfA"
message = "Got info successfully"
registration_port = 4875
state = "GotInfo"
subnet = "fd00::1337:1e0f/128"
subnet_len = 128
wg_public_key = "zgAlhyOQy8crB0ewrsWt3ES9SvFguwx5mq9i2KiknmA="

[exit_client.new_exits.test.general_details]
description = "Test cluster: A!"
exit_currency = "Rinkeby"
exit_price = 714000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.new_exits.test.id]
eth_address = "0x5AeE3Dff733F56cFe7E5390B9cC3A46a90cA1CfA"
mesh_ip = "fd00::1337:1e0f"
wg_public_key = "zgAlhyOQy8crB0ewrsWt3ES9SvFguwx5mq9i2KiknmA="

[exit_client.new_exits.test.selected_exit]
selected_id = "fd00::1337:1e0f"

[exit_client.new_exits.us_west]
description = "The Althea Production US exit"
eth_address = "0x72d9E579f691D62aA7e0703840db6dd2fa9fAE21"
message = "Registration OK"
registration_port = 4875
state = "Registered"
subnet = "fd00::1000:e2f/116"
subnet_len = 116
wg_public_key = "jkIodvXKgij/rAEQXFEPJpls6ooxXJEC5XlWA1uUPUg="

[exit_client.new_exits.us_west.general_details]
description = "Althea San Francisco Exit Equinix"
exit_currency = "Xdai"
exit_price = 10000000
netmask = 16
server_internal_ip = "172.168.0.254"
verif_mode = "Phone"
wg_exit_port = 59999

[exit_client.new_exits.us_west.id]
eth_address = "0x72d9E579f691D62aA7e0703840db6dd2fa9fAE21"
mesh_ip = "fd00::1337:e2f"
wg_public_key = "jkIodvXKgij/rAEQXFEPJpls6ooxXJEC5XlWA1uUPUg="

[exit_client.new_exits.us_west.our_details]
client_internal_ip = "172.168.2.146"

[exit_client.new_exits.us_west.selected_exit]
selected_id = "fd00::1000:e2f"

[localization]
display_currency_symbol = true
wyre_enabled = true
[localization.support_number.code]
source = "plus"
value = 1

[localization.support_number.national]
value = 8664258432
zeros = 0

[log]
dest_url = "https://stats.altheamesh.com:9999/compressed_sink/"
enabled = true
level = "WARN"

[network]
babel_port = 6872
backup_created = false
bounty_port = 8888
device = "ubnt-erx"
discovery_ip = "ff02::1:8"
light_client_hello_port = 4878
light_client_router_ip = "192.168.30.1"
manual_peers = ["africa.althea.net", "ca.althea.net", "sa-eth.althea.org", "apac.altheamesh.com", "test.althea.org", "exit.altheamesh.com", "borked.altheamesh.com", "sa.althea.org"]
mesh_ip = "fd22:99f8:27fb:133:151c:21f5:c6d:2684"
metric_factor = 1900
nickname = "dev er-x"
peer_interfaces = ["eth2", "mesh", "eth4", "eth3"]
rita_contact_port = 4874
rita_dashboard_port = 4877
rita_hello_port = 4876
rita_tick_interval = 5
usage_tracker_file = "/etc/rita-usage-tracker.json"
user_set_release_feed = false
wg_private_key = "mFjBODCtBLZX8crTVTGNDzNp2eX6mXRt7h//74qvE3g="
wg_private_key_path = "/tmp/priv"
wg_public_key = "0ndIJn8F48AwkIdbULEHK+18bgwYzIhxVryRFbPNuyQ="
wg_start_port = 60000

[network.last_default_route]
metric = 600
nic = "wlp0s20f3"
proto = "dhcp"
via = "192.168.1.254"

[network.shaper_settings]
enabled = true
max_speed = 300
min_speed = 30

[operator]
display_operator_setup = false
force_use_operator_price = false
operator_address = "0xd18B87EBaaeBca53b63d5310e3B4D1bC2c68dda6"
operator_fee = "7610350076104"
use_operator_price = true

[payment]
apply_incoming_credit_immediately = false
balance = "19251608744581815810"
balance_warning_level = "10000000000000000000"
bridge_enabled = true
client_can_use_free_tier = true
close_threshold = "-504000000000000000"
debt_limit_enabled = true
debts_file = "/etc/rita-debts.json"
dynamic_fee_multiplier = 6000
eth_address = "0xaAf215E8bA84e7813d4bf91739FE41Df5036CC04"
eth_private_key = "0x669762ed5d47312fd3ccc251fdf798955200b4cd3048a1bcc6396b611c1fd19a"
forgive_on_reboot = true
free_tier_throughput = 1000
fudge_factor = 0
gas_price = "1000000000"
light_client_fee = 10000000
local_fee = 30000000
max_fee = 1000000000
max_gas = 1000000000
min_gas = 1000000000
net_version = 100
node_list = ["https://dai.althea.org:443"]
nonce = "88"
pay_threshold = "126000000000000000"
simulated_transaction_fee = 10
simulated_transaction_fee_address = "0xEE8BBA37508cd6f9dB7c8AD0AE2b3DE0168c1b36"
system_chain = "Xdai"
withdraw_chain = "Ethereum"

[payment.bridge_addresses]
eth_full_node_url = "https://eth.althea.org"
helper_on_xdai = "0x6A92e97A568f5F58590E8b1f56484e6268CdDC51"
xdai_bridge_on_eth = "0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016"
xdai_bridge_on_xdai = "0x7301CFA0e1756B71869E93d4e4Dca5c7d0eb0AA6"
xdai_full_node_url = "https://dai.althea.org"