[package]
name = "num256"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]
license = "Apache 2.0"

[dependencies]
num = "0.1.41"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"