[package]
name = "althea_types"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
array_serialization_derive = { path = "../array_serialization_derive" }

base64 = "0.9.0"
serde_derive = "1.0.24"
serde = "1.0.24"
serde_json = "1.0.8"
hex = "0.3.1"