[package]
name = "althea_types"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
num256 = { path = "../num256" }
base64 = "0.9.2"
serde_derive = "1.0.70"
serde = "1.0.70"
serde_json = "1.0.24"
hex = "0.3.2"
eui48 = { git = "https://github.com/althea-mesh/eui48", features = ["serde"] }
actix = { version = "0.7.3", optional = true }
ethereum-types = {git="https://github.com/paritytech/primitives.git"}
