[package]
name = "clu"
version = "0.0.1"
authors = ["Justin <kilpatrickjustin@protonmail.ch>"]

[dependencies]
settings = { path = "../settings" }
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types" }
lazy_static = "1.0.2"
docopt = "0.8.3"
log = "0.4.3"
env_logger = "0.5.11"
failure = "0.1.2"
ipgen = "0.0.4"
regex = "1.0.2"
rand = "0.5.4"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
